language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
addons:
  firefox: latest-esr
env:
- PLONE_VERSION=4.2 TEST_EGGS=Pillow
- PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout buildout:test-eggs=$TEST_EGGS annotate
- bin/buildout buildout:test-eggs=$TEST_EGGS
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
